import type { Metadata } from 'next'
import { Montserrat, Urbanist } from 'next/font/google'
import './globals.css'
import RootLayoutClient from './RootLayoutClient';
import { Session } from 'next-auth';

const font = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})


export const metadata: Metadata = {
  title: 'BCS - Creating Opportunities',
  keywords: ['BCS', 'Business', 'Opportunities', 'Growth', 'Innovation'],
  description: 'Generated by create next app',
}

export default function RootLayout({ children, session }: { children: React.ReactNode, session: Session }) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-white dark:bg-black antialiased`}>
        <RootLayoutClient session={session}>{children}</RootLayoutClient>
      </body>
    </html>
  );
}